### ISSUE TITLE
Rolling on size

### ISSUE THREAD

**Issue by milan-vidakovic-work** [serilog/serilog-extensions-logging-file#18]
Is there a way of getting the log files to roll on max size exceeded?

Cheers!

**Comment by nblumhardt** [comment]
Hi Milan, thanks for the note.

Yes, this could be done by shifting the implementation over to use the new features in _Serilog.Sinks.File_ - https://nblumhardt.com/2017/10/serilog-file-logging/

Keeping the API consistent might require a little bit of compatibility code (i.e. continuing to accept `{Date}` placeholders if they're the last (non-extension) part of the filename), but nothing that would block the feature.

If anyone's keen to PR this I can help get it through 👍

**Comment by milan-vidakovic-work** [comment]
Hi Nicholas, thank you for the prompt response. 

I'd like to take a crack at it, just need to figure out if my current schedule has a bit of wiggle room.

If I understand correctly, the functionality is already there, but the Core extension uses the outdated Sinks package. So, rewiring to the new Sinks, and adding a bit of the old extension's legacy code would do the trick?

Thank you

**Comment by nblumhardt** [comment]
Yes, switching to _Serilog.AspNetCore_ + the new _Serilog.Sinks.File_ would achieve this, too 👍 

If you're still interested in updating _Serilog.Extensions.Logging.File_, the basic change would be to call `WriteTo.File()` under the hood, rather than `WriteTo.RollingFile()`.

Apart from also allowing rolling on file size, `WriteTo.File()` does not expect `{Date}` placeholders in paths.

So, if the path passed to `AddFile()` has `{Date}` at the end of the filename part, it would need to be removed.

If the path being configured doesn't end in `{Date}`, the old rolling file would append `-{Date}` itself, so, to achieve the same file naming pattern, `AddFile()` would need to append a `-` to the filename part.

Paths with `{Date}` anywhere but at the end of the filename would have to be unsupported (we'd either throw an exception, or just remove the `{Date}` part and accept that the file naming pattern would change.

Cheers!

**Comment by milan-vidakovic-work** [comment]
I needed to act rather quickly, because my staging env was hemorrhaging logs. I switched to full serilog + sinks.file setup, and it all went seamlessly easy. So easy, that you might even consider deprecating the file output extension :).

One think I've noticed, the serilog.aspnetcore readme uses <2.0 .net core initialization standards. 
For instance: 
```c#
var host = new WebHostBuilder()
.UseStartup<Startup>()
.UseSerilog()
.Build();
```
in 2.0 turns into 
```c#
 WebHost.CreateDefaultBuilder(args)
.UseStartup<Startup>()
.UseSerilog()
.Build();
```

Just pointing this out because the repository is marked as Serilog integration for ASP.NET Core 2+.

Also, I couldn't get it to work in 2.0 until I moved the logger configuration init
```c#
Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.File("some-path.log")
            .CreateLogger()
```

to mu Startup.cs - was getting SilentLogger instances.

Thanks again - great job!

**Comment by nblumhardt** [comment]
Thanks - README is now updated 👍

**Comment by nblumhardt** [comment]
Now that you mention it - this is probably feature creep, and we should keep directing people to use the full Serilog integration when they need features not available here in the basic file provider. Will close for now. Thanks!
