### ISSUE TITLE
String arguments for message are enclosed in double quotes - different from other loggers

### ISSUE THREAD

**Issue by kwaclaw** [serilog/serilog-extensions-logging-file#7]
Within the Asp.Net Core logging infrastructure, the default rendering of format arguments should be the same.  Example: 

`LogInformation("This is {0}", "an error")`  is expected to render as:    **This is an error**

However, with Serilog it renders as:    **This is "an error"**

Although this can be fixed supposedly by adding the :l specifier, I do not want to add Serilog specific modifiers, as I have other loggers that are used with the same messages concurrently.

**Comment by nblumhardt** [comment]
Thank you for the note.

When Serilog renders data, it uses a JSON-like representation, so strings end up `"like this"` while numbers are `123` and arrays `[1, 2, 3]` etc.

Opting out at the level of individual tokens (`{0:l}`) doesn't really achieve what you want here, as you pointed out. It'd be nicer to override the rendering at a higher level.

We could do this in the current repository, by using a custom formatter instead of `MessageTemplateTextFormatter` here:

https://github.com/serilog/serilog-extensions-logging-file/blob/dev/src/Serilog.Extensions.Logging.File/Microsoft/Extensions/Logging/FileLoggerExtensions.cs#L118

```csharp
var formatter = isJson ?
    (ITextFormatter)new RenderedCompactJsonFormatter() :
    new MessageTemplateTextFormatter("{Timestamp:o} {RequestId,13} [{Level:u3}] {Message} ({EventId:x8}){NewLine}{Exception}", null);
```

Another alternative would be to modify `MessageTemplateTextFormatter`'s handling of `{Message}` so that the `:l` is applied to the tokens within the message; e.g.:

```csharp
"{Timestamp:o} {RequestId,13} [{Level:u3}] {Message:l} ({EventId:x8}){NewLine}{Exception}"
```

This'd have to be done in serilog/serilog, but might have wider benefit than special-casing it just for the file provider here.

@serilog/reviewers-core I'm curious what you think about this one; on the one hand, it's friendly to provide the switch (and may sit better alongside MEL), but on the other hand, it's more complexity to carry around... Impressions?

**Comment by adamchester** [comment]
I think this issue comes up often enough that it deserves to be in serilog/serilog.

**Comment by nblumhardt** [comment]
:+1: Moved to the issue linked above.
